### PR TITLE
Added the possibility to copy parameters

### PR DESCRIPTION
**Pull request by beeekey**
Added the possibility to copy parameters from an already generated image to the clipboard to put it back into the prompt. It is now implemented for the prompt, the negative prompt and the seed

### CODE REVIEW

**Comment by ndahlquist** [comment]
@beeekey @Khosbayar , rather than individual copy buttons, I was thinking maybe we should have a button that automatically copies all parameters from an image (and jumps you back over to the "dream" tab). That would save the user some time if there is an image they are trying to recreate (instead of having to manually copy every parameter).

Thoughts? (open to discussion on this).

I want to say [Stable UI](https://aqualxx.github.io/stable-ui/) has a feature like this, but I seem to be hitting a bug and am unable to see images show up in the "Images" tab.

Also- I realized that we should make the text manually copyable by pressing and holding in the normal way (it's disabled by default in Flutter). I've made that change on main.

**Comment by beeekey** [comment]
I didn't dive to deep now into Stable Horde Flutter and never used BLOC, so please be patient. 

I'm not sure, how to pass all parameters to the "dream" tab. Is this done over shared preferences? 

I would suggest two buttons, one for copying all the parameters and one to copy the parameters without the seed.

**Comment by ndahlquist** [comment]
> Is this done over shared preferences?

Yes exactly! `await sharedPrefsBloc.setPrompt(newPrompt);`, etc.

> I would suggest two buttons, one for copying all the parameters and one to copy the parameters without the seed.

This sounds reasonable, although I think it might be confusing what the difference between the two buttons are (will need to be careful with the description).

**Comment by ndahlquist** [comment]
Oh, and then to animate over to the home page, we can call `homeController.animateToPage(0)`.

**Comment by beeekey** [comment]
I tried to implement it. No worries if you have to clean/change stuff. I'm relatively new to flutter.

**Pull request merged**
